### ISSUE TITLE
Allow empty response data, or none at all?

### ISSUE THREAD

**Issue by Gwildor** [wendbv/shampoo#5]
Sometimes, a response doesn't make sense. Perhaps sometimes an acknowledgement is enough. At the moment, `response_data` in a response has to be an object, but I'm proposing to make it optional. If the endpoint method returns `None`, it isn't added.

**Comment by martijnarts** [comment]
Do you have an example of a type of endpoint that wouldn't return any data?

**Comment by Gwildor** [comment]
Endpoints that delete an entity, such as `delete_chapter` and `delete_chapter_item`. And maybe also endpoints that reorder things, like `shift_chapter_order` and `shift_chapter_item_order` (these are the ones where I ran into this, although they might actually return something later).

**Comment by dporru** [comment]
I agree that makes sense. We also could allow a `null` value, but I find that less clean.

**Comment by martijnarts** [comment]
I'm not sure on either of those. Delete actions could very well still respond with the new state of the item (which would either be null or an empty object) and shifting actions may want to reply with the new state of the collection?

**Comment by dporru** [comment]
I had the same feeling at first. But with issue #6, I think shampoo just shouldn't concern itself at all with the `response_data`. It can exist and if it does it needs to be encodable to `json`. The rest is up to the implementer.

**Comment by dporru** [comment]
I'm getting back on this one as well. I think it is easier for the client if `response_data` is always an object.
