### ISSUE TITLE
Response should be validated *after* json encoding

### ISSUE THREAD

**Issue by Gwildor** [wendbv/shampoo#6]
At the moment a custom json encoder doesn't give a lot of benefit because the response is validated against `response.json` before a custom json encoder comes into play. The specific problem I ran into is our custom encoder which transforms Python datetime objects to ISO 8601 strings, which we accept in our schemas. Telling shampoo to use our custom encoder did not help because of this issue.

This might be troublesome because I'm not sure if `jsonschema` actually accepts json objects instead of Python dictionaries.

**Comment by dporru** [comment]
We shouldn't check the response at runtime, as we create response object ourselves. The check should be moved to the tests.

**Comment by dporru** [comment]
I don't agree with myself anymore. The runtime validation is there to ensure the response is always a valid `response.json`.
New sollution: if there is a custom encoder, encode the `response_data` with this custom encoder and than decode with the default encoder, so `jsonschema` can handle the result.
